require "time"

module Versync
  module Renderers
    class Markdown
      HEADER = "<!-- Generated by versync. Do not edit by hand — run `versync sync`. -->"

      def initialize(facts:, generated_at:, commit:)
        @facts = facts
        @generated_at = generated_at
        @commit = commit
      end

      def render
        <<~MD
          #{HEADER}

          # Repository Facts

          #{table}

          _Last synced: #{@generated_at.utc.iso8601} · commit #{@commit || "unknown"}_
        MD
      end

      private

      def table
        return "_No facts available._" if @facts.empty?

        rows = @facts.map { |fact| "| #{fact.name} | #{fact.value} | #{fact.source} |" }
        (["| Fact | Version | Source |", "|---|---|---|"] + rows).join("\n")
      end
    end
  end
end
