require "test_helper"
require "time"

module Renderers
  class MarkdownTest < Minitest::Test
    def test_renders_a_facts_table_with_header_and_footer
      facts = [
        Versync::Fact.new(name: "ruby", value: "4.0.6", source: ".ruby-version"),
        Versync::Fact.new(name: "rails", value: "8.1.3", source: "Gemfile.lock")
      ]
      generated_at = Time.parse("2026-08-25T12:00:00Z")

      output = Versync::Renderers::Markdown.new(facts: facts, generated_at: generated_at, commit: "abc123").render

      assert_includes output, "<!-- Generated by versync. Do not edit by hand — run `versync sync`. -->"
      assert_includes output, "| Fact | Version | Source |"
      assert_includes output, "| ruby | 4.0.6 | .ruby-version |"
      assert_includes output, "| rails | 8.1.3 | Gemfile.lock |"
      assert_includes output, "_Last synced: 2026-08-25T12:00:00Z · commit abc123_"
    end

    def test_renders_unknown_when_commit_is_nil
      output = Versync::Renderers::Markdown.new(facts: [], generated_at: Time.parse("2026-08-25T12:00:00Z"), commit: nil).render
      assert_includes output, "commit unknown"
    end

    def test_renders_placeholder_when_no_facts
      output = Versync::Renderers::Markdown.new(facts: [], generated_at: Time.parse("2026-08-25T12:00:00Z"), commit: "abc").render
      assert_includes output, "_No facts available._"
      refute_includes output, "| Fact | Version | Source |"
    end
  end
end
